### ISSUE TITLE
Crashes sometimes on handle_nickreply

### ISSUE THREAD

**Issue by ArkaneMoose** [jedevc/EuPy#2]
Traceback provided below, with some information omitted.

```
Traceback (most recent call last):
  File "/path/bot.py", line xx, in <module>
    main()
  File "/path/bot.py", line xx, in main
    eu.executable.start(bot)
  File "/path/euphoria/executable.py", line 37, in start
    e.run()
  File "/path/euphoria/room.py", line 100, in run
    if self.connection.receive_data():
  File "/path/euphoria/connection.py", line 118, in receive_data
    self.handle_packet(json.loads(raw))
  File "/path/euphoria/connection.py", line 158, in handle_packet
    callback(packet)
  File "/path/euphoria/nick_room.py", line 32, in handle_nickreply
    self.nickname = data["data"]["to"]
TypeError: 'NoneType' object is not subscriptable
```

I suspect this occurs when the `nick-reply` packet is to inform the client of an error; when this happens, `data` is `null`, which becomes `None` in Python's JSON library. The error occurs because `data["data"]` is `None`, so the line becomes `self.nickname = None["to"]`, which causes the `TypeError`.

**Comment by jedevc** [comment]
Thank you @ArkaneMoose. Let me know if this fixes it.
